name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Push package to npmjs.com
      uses: actions/setup-node@v4
      with:
        node-version: 17
        registry-url: https://registry.npmjs.org/
    - run: npm install
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
